### PR TITLE
Add more metadata files

### PR DESCRIPTION
**Pull request by bethac07**
Added new tables describing 1) the CellProfiler version used in each source as well as 2) the channel mapping. Marked as a draft for now because a) still haven't scripted the consistency-check on the channel mapping but also b)I don't know how to do the fancy mapping thing

### CODE REVIEW

**Comment by shntnu** [comment]
> I don't know how to do the fancy mapping thing

Now addressed in the last 3 commits

**Comment by shntnu** [comment]
> still haven't scripted the consistency check on the channel mapping

@bethac07 this might not be the week to work on anything not super critical :D 

I just wanted to put this back on your radar for the near future

Here's the file again:

https://github.com/jump-cellpainting/datasets/blob/181fa0dc96b0d68511b437cf75a712ec782576aa/metadata/channel_mapping.csv

**Comment by bethac07** [comment]
Yes, that's the task, which I don't think is actually hard but is clearly not going to rise to the top of my todos in the next 6 months. Fine to split and then merge what we have.

**Comment by shntnu** [comment]
Sounds good. I will drop in the patch here

```    
    PLATE }|--|| CHANNEL-MAPPING : ""
    CHANNEL-MAPPING {
        string Metadata_Source "Data-generating center ID"
        int Metadata_Channel_Num_DNA "DNA channel number"
        int Metadata_Channel_Num_ER "ER channel number"
        int Metadata_Channel_Num_RNA "RNA channel number"
        int Metadata_Channel_Num_AGP "AGP channel number"
        int Metadata_Channel_Num_Mito "Mito channel number"
        int Metadata_Channel_Num_BFLowest "Brightfield-Lowest channel number"
        int Metadata_Channel_Num_BFMedium "Brightfield-Medium channel number"
        int Metadata_Channel_Num_BFHighest "Brightfield-Highest channel number"
    }   
    ```

**Pull request merged**
