### PR TITLE
Add SMILES to compounds.csv.gz

### PR DESCRIPTION
**Pull request by srijitseal**
This file adds a standardized SMILES column and the first 14 characters of the InChI key (representing the connectivity) to the compounds.csv.gz We show that six compounds have dual entires, often different ionization states.

### CODE REVIEW

**Comment by shntnu** [comment]
Over to @afermg to review

@srijitseal I noticed a few things that would need fixing, but let's wait for @afermg 's full review

- Column names should start with `Metadata_`
- Provide source code used for standardization. @afermg will decide where this should live. Recap: We have a standardizer here https://github.com/jump-cellpainting/compound-annotator/blob/main/StandardizeMolecule.py that was used to produce the InChiKeys in compound.csv.gz. If @srijitseal's code's logic is very similar, then Srijit should update that code base to allow processing using his logic. If the logic is very different, then we should do something different (@afermg can advise on what to do)
- Update the README https://github.com/jump-cellpainting/datasets/tree/main/metadata to indicate how the SMILES were standardized
- Update the schema in https://github.com/jump-cellpainting/datasets/blob/main/metadata/README.md

**Comment by afermg** [comment]
@srijitseal Could you please point me to the code? I think it can go to monorepo, but we must first package it as a small library for reproducibility. The most important things at the moment is pinning the dependencies. Let me know if I can be of help for that.

**Comment by srijitseal** [comment]
https://github.com/jump-cellpainting/jump-cellpainting/pull/156
You can find the file here! Is almost the same but I removed the loop to
save time after consulting with Andreas, I think the efficiency to
standardize now is 6 times faster for less loss of information and
tautomers will always remain a problem no matter which package we use or
how many loops we run for boring the best tautomer.

**Comment by afermg** [comment]
The comment on pinning dependencies is only for reproducibility, I am not knowledgeable enough about chemoinformatics to comment about the usage of those library. I do need the dependency versions and one test to ensure that packaging still works. 

Sorry if it seems like I'm asking for a lot, I just want to ensure that the code that we put in the monorepo runs correctly so it can be reliably referred to in the future. Also, because it is to be a tiny tool, we need to have it as a script/module, not a notebook. I can do the transformation though, as long as I can reproduce the environment in which you produced the data.

**Comment by shntnu** [comment]
I overrode this PR for now by using the SMILES generated when the JCP IDs were created
Details: https://github.com/jump-cellpainting/datasets-private/pull/88

**Pull request merged**
